### ISSUE TITLE
Remove dependency of objectbridge

### ISSUE THREAD

**Issue by jorisros** [YouweGit/data-dictionary#13]
I think we must try to remove the dependency of the objectbridge. That we try to move the logic of including the objectBridge to the objectBridgeBundle it self.

I think we have more flexibility in the future, it will easier to extend in the future. Because we have other relation types and you don't want to include them all in this bundle.

**Comment by paulovitorbal** [comment]
I agree with you. I will take a deeper look at what are the methods that we need and will make some refactoring to achieve this.

**Comment by jorisros** [comment]
Maybe a event listener where you can subscribe on.

**Comment by paulovitorbal** [comment]
fixed by creating a new bundle to make the packages not dependent on each other
